pipeline {
  
  agent { label 'docker' } 

    
    stage("docker build-and-push-image"){
      when{
        changeset "**/vote/**"
      }
      steps{
        container('kaniko'){
          sh 'ls -lah'
          sh 'cd vote; ls -lah; /kaniko/executor --context `pwd` --verbosity debug --destination harbor2.btech.id/library/vote:main'
        }
      }
    }


  }
  post{
    always{
      echo 'Pipeline Complete'}
  }
}
